services:
  vllm:
    image: vllm/vllm-openai:latest
    container_name: vllm-gptoss

    ports:
      - "8000:8000"

    environment:
      HF_TOKEN: ${HF_TOKEN}
      VLLM_API_KEY: ${VLLM_API_KEY}

    volumes:
      - ./hf-cache:/root/.cache/huggingface

    ipc: host

    command:
      - --model
      - ${MODEL_NAME}
      - --host
      - 0.0.0.0
      - --port
      - "8000"
      - --api-key
      - ${VLLM_API_KEY}
      - --dtype
      - ${DTYPE}
      - --gpu-memory-utilization
      - ${GPU_MEMORY_UTIL}
      - --max-model-len
      - ${MAX_MODEL_LEN}
      - --max-num-seqs
      - ${MAX_NUM_SEQS}

    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: ${GPU_COUNT}
              capabilities: [gpu]

  chat-ui:
    build:
      context: ./chat-ui
    container_name: vllm-chat-ui
    depends_on:
      - vllm
    ports:
      - "3000:3000"
    environment:
      VLLM_BASE_URL: http://vllm-gptoss:8000/v1
      VLLM_API_KEY: ${VLLM_API_KEY}
      MODEL_NAME: ${MODEL_NAME}
